### ISSUE TITLE
Can't connect on app

### ISSUE THREAD

**Issue by Laurentius26** [quantadex/react_quantadex#151]
My browser is working fine but I can't connect, it says server error. 
![Screenshot_20190513-221821](https://user-images.githubusercontent.com/35572301/57651730-4b62f500-75ce-11e9-8713-9e9f9e58809f.jpg)
![Screenshot_20190513-222017](https://user-images.githubusercontent.com/35572301/57651750-5584f380-75ce-11e9-8016-28a8c07f828a.jpg)

**Comment by quocble** [comment]
Thanks for reporting it.

Is this preventing you to login from the mobile app?
Does it work on desktop?

**Comment by Laurentius26** [comment]
Your welcome, yes it's preventing me to login from the mobile app, on desktop I have no problem to login.

**Comment by quocble** [comment]
@Laurentius26  We pushed build to production. Please confirm if it resolves the issue.

**Comment by Laurentius26** [comment]
Thank but I already use the version in the Googleplay appstore and there 's no update. When I try to connect I still get 'server error.Please try again'.

**Comment by Laurentius26** [comment]
To update you, the issue is still there, I'm using Android version 1.0.13 of the Quantadex app.

**Comment by TinyMolecule** [comment]
Are other parts of the app working for you when you try to login?

**Comment by Laurentius26** [comment]
Thank you, all of a sudden it's possible to login again using the app. Weird as it didn't work a couple of days. Anyway, consider it solved.
